### ISSUE TITLE
Refactoring from script based solution to OOP

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/living-doc-generator#3]
The first goal is to release the PoC solution.

```[tasklist]
### Tasks
- [ ] https://github.com/AbsaOSS/living-doc-generator/issues/4
- [ ] https://github.com/AbsaOSS/living-doc-generator/issues/7
- [ ] https://github.com/AbsaOSS/living-doc-generator/issues/8
- [x] https://github.com/AbsaOSS/living-doc-generator/issues/17
- [x] https://github.com/AbsaOSS/living-doc-generator/issues/19
- [x] https://github.com/AbsaOSS/living-doc-generator/issues/21
- [ ] https://github.com/AbsaOSS/living-doc-generator/issues/9
- [ ] https://github.com/AbsaOSS/living-doc-generator/issues/10
- [ ] https://github.com/AbsaOSS/living-doc-generator/issues/11
- [ ] https://github.com/AbsaOSS/living-doc-generator/issues/23
- [ ] https://github.com/AbsaOSS/living-doc-generator/issues/13
- [x] https://github.com/AbsaOSS/living-doc-generator/issues/25
- [ ]  https://github.com/AbsaOSS/living-doc-generator/issues/12
```

Notes:
- **GH Token scope**: Observed failures when trying to data mine data out of token scope. Unrelated repos from absa-group. This was not detected in the origin repository.
- **GH limit rate**: Observed random data mining failures/instabilities during initial action development.

**Comment by miroslavpojer** [comment]
Closing as all Tasks solved.
